0_torch_fundamental

In [9]:
import numpy as np

In [1]:
import torch
print(torch.__version__)


2.8.0+cu126


In [2]:
# اول حاجه هننشاء Tensor
ten=torch.tensor([[1,2],[3,4]],  dtype=torch.float32)
print("tensor:", ten)


tensor: tensor([[1., 2.],
        [3., 4.]])


In [3]:
rand_tensor = torch.rand((2, 3))
print("\nRandom Tensor:\n", rand_tensor)


Random Tensor:
 tensor([[0.7752, 0.0593, 0.4699],
        [0.4611, 0.1396, 0.2554]])


In [4]:
zeros = torch.zeros((2, 2))
ones = torch.ones((2, 2))
print("\nZeros:\n", zeros)
print("Ones:\n", ones)


Zeros:
 tensor([[0., 0.],
        [0., 0.]])
Ones:
 tensor([[1., 1.],
        [1., 1.]])


In [8]:
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# الجمع والطرح
sum_result = ten + y
sub_result = y - ten

# الضرب العنصري والمصفوفي
mul_result = ten * y
matmul_result = torch.matmul(ten, y)

print("\nSum:\n", sum_result)
print("\nSubtraction:\n", sub_result)
print("\nElement-wise Multiply:\n", mul_result)
print("\nMatrix Multiply:\n", matmul_result)



Sum:
 tensor([[ 6.,  8.],
        [10., 12.]])

Subtraction:
 tensor([[4., 4.],
        [4., 4.]])

Element-wise Multiply:
 tensor([[ 5., 12.],
        [21., 32.]])

Matrix Multiply:
 tensor([[19., 22.],
        [43., 50.]])


In [12]:
# Tensor إلى NumPy
numpy_array = ten.numpy()
print("\nTensor to NumPy:\n", numpy_array)

# NumPy إلى Tensor
new_tensor = torch.from_numpy(numpy_array)
print("\nNumPy to Tensor:\n", new_tensor)



Tensor to NumPy:
 [[1. 2.]
 [3. 4.]]

NumPy to Tensor:
 tensor([[1., 2.],
        [3., 4.]])


In [13]:
a = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(4.0, requires_grad=True)

# دالة بسيطة z = a² + 2b
z = a**2 + 2*b

# حساب المشتقات
z.backward()

print("\nGradient of a:", a.grad)
print("Gradient of b:", b.grad)



Gradient of a: tensor(6.)
Gradient of b: tensor(2.)
